# Generated by Django 5.2.14 on 2026-05-18 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterclasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclasses.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='booking',
            name='masterclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterclasses.masterclass', verbose_name='Мастер-класс'),
        ),
    ]
