# Generated by Django 5.2.14 on 2026-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='schedule',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
    ]
